{
 "title": "Capacity planning",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, container)"
    }
   },
   { "name": "quantile", "query": "99,50,90,95,999" }
  ]
 },
 "panels": [
  {
   "title": "Overview CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Overview Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{namespace=\"$namespace\"}[$__rate_interval])) by (container) / (1024 * 1024 *1024)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Resource waste", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "namespace CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "total requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "total limits"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"})",
     "legendFormat": "total usage"
    }
   ]
  },
  {
   "title": "namespace memory  usage (Gi)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\", resource=\"memory\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "total requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "total limits"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) / (1024 * 1024 *1024)",
     "legendFormat": "total usage"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$container\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$container\", resource=\"cpu\"})",
     "legendFormat": "current CPU requests"
    },
    {
     "expr": "avg(avg_over_time( (\n    irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}[$__rate_interval])\n  )[$__range:]\n))",
     "legendFormat": "suggested CPU request"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$container\", resource=\"cpu\"})",
     "legendFormat": "current CPU limit"
    },
    {
     "expr": "max(max_over_time( (\n    irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}[$__rate_interval])\n  )[$__range:]\n))",
     "legendFormat": "suggested conservative CPU limit"
    },
    {
     "expr": "max(quantile_over_time(0.$quantile, (\n    irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}[$__rate_interval])\n  )[$__range:]\n))",
     "legendFormat": "suggested agressive CPU limit"
    }
   ]
  },
  {
   "title": "Memory (Gi)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=\"$container\"} / (1024 * 1024 *1024)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$container\", resource=\"memory\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "current requests"
    },
    {
     "expr": "avg(avg_over_time(container_memory_usage_bytes{namespace=\"$namespace\", container=\"$container\"}[$__range]) / (1024 * 1024 *1024))",
     "legendFormat": "suggested memory request"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$container\", resource=\"memory\"}) / (1024 * 1024 * 1024)",
     "legendFormat": "current limit"
    },
    {
     "expr": "max(max_over_time(container_memory_usage_bytes{namespace=\"$namespace\", container=\"$container\"}[$__range]) / (1024 * 1024 *1024))",
     "legendFormat": "suggested conservative memory limit"
    },
    {
     "expr": "avg(quantile_over_time(0.$quantile,container_memory_usage_bytes{namespace=\"$namespace\", container=\"$container\"}[$__range]) / (1024 * 1024 *1024))",
     "legendFormat": "suggested agressive memory limit"
    }
   ]
  },
  { "title": "Resource issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Detecting containers with very tight CPU limits",
   "type": "timeseries",
   "description": "(sum by (namespace,pod,container)(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) / sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"})) > 0.8",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "(sum by (pod,container)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\"}[$__range])) / sum by (pod,container)(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})) > 0.$quantile"
    }
   ]
  },
  {
   "title": "Detecting containers with very tight memory limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "(sum by (pod,container)(container_memory_usage_bytes{namespace=\"$namespace\", container!=\"\"}) / sum by (pod,container)(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"})) > 0.$quantile"
    }
   ]
  },
  {
   "title": "Containers without CPU limits in namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum (count by (pod,container)(kube_pod_container_info{namespace=\"$namespace\", container!=\"\"}) unless sum by (pod,container)(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (pod,container)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\"}[$__range])) / sum by (pod,container)(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"})) > 0.$quantile"
    }
   ]
  },
  {
   "title": "Containers without memory limits in namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum (count by (pod,container)(kube_pod_container_info{namespace=\"$namespace\", container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "Containers without memory requests by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum (count by (pod,container)(kube_pod_container_info{namespace=\"$namespace\", container!=\"\"}) unless sum by (pod,container)(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "Containers without CPU requests by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum (count by (pod,container)(kube_pod_container_info{namespace=\"$namespace\", container!=\"\"}) unless sum by (pod,container)(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}))"
    }
   ]
  }
 ]
}